### ISSUE TITLE
US-2 Game Configuration for Development

### ISSUE THREAD

**Issue by halyngoc** [halyngoc/CS300-Group3-SpaceHunt#3]
Estimate:
Actual:

User Story: US-2
Game Configuration for Development
Priority: 1

Story: As a developer, I want to customize my game play by selecting initial values for the state
variables: location, energy, supplies, credits, fixed wormhole behavior random wormhole behavior,
regular play/never dies, MAX game size so I can avoid setting these values through normal game play

Acceptance Criteria:
AC.1 Passed
AC.2
AC.3
AC.4 Passed
AC.5 Passed

1. Verify that if set the MAX to k, subsequent attempts to move beyond k results in wormhole behavior
2. Verify that if set to “never dies” the player can continue playing in spite of have zero or negative
energy and/or supplies.
3. Verify that if set to “regular play” the player dies when running out of energy or supplies
4. Verify that if set to random wormhole behavior, when player is relocated, they are relocated to a
random CP
5. Verify that if set to fixed wormhole behavior, when play is relocated, they are relocated to a
specified CP

**Comment by LiamRotchford5671** [comment]
Code integrated with Simon's US-1. Currently criteria 1 , 4, and 5 have been implemented, tested, and passed. Waiting on a updated version of US 4/5 that will work with Simon's newer javascript file but have code saved that should work perfectly once that is received, will just need to test to pass criteria 2 and 3.
